name: tradefolio
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

#------------------------ PACKAGES ------------------------#

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  shimmer: ^3.0.0
  rename: ^3.0.2
  iconsax:
  flutter_floating_bottom_bar: ^1.2.1+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

#---------------------- DEV PACKAGES ----------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #----------------------- LOCAL ASSETS ----------------------#
  assets:
    - assets/icons/
    - assets/images/
